name: CI - Train Model (MLflow Project)

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Upgrade pip & install mlflow
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==3.6.0
        mlflow --version


    - name: Install project dependencies
      run: |
        pip install -r MLProject/requirements.txt

    - name: Run MLflow Project (no-conda)
      run: |
        mlflow run MLProject --no-conda \
          -P csv_path="namadataset_preprocessing.csv" \
          -P target_col="GRADE" \
          -P task="auto"


    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: MLProject/artifacts/
